# FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
# USER $APP_UID
# WORKDIR /app
# ENV ASPNETCORE_URLS=http://+:5000
# EXPOSE 5000

# FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
# ARG BUILD_CONFIGURATION=Release
# WORKDIR /src
# COPY ["api/DateTimeApi.csproj", "api/DateTimeApi/"]
# RUN dotnet restore "api/DateTimeApi.csproj"
# COPY . .
# WORKDIR "/src/api/DateTimeApi"
# RUN dotnet build "./DateTimeApi.csproj" -c $BUILD_CONFIGURATION -o /app/build

# FROM build AS publish
# ARG BUILD_CONFIGURATION=Release
# RUN dotnet publish "./DateTimeApi.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

# FROM base AS final
# WORKDIR /app
# COPY --from=publish /app/publish .
# ENTRYPOINT ["dotnet", "DateTimeApi.dll"]

FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/sdk:9.0-alpine AS build
ARG TARGETARCH
WORKDIR /src

COPY DateTimeApi.csproj .
RUN dotnet restore -a ${TARGETARCH}

COPY Program.cs .
RUN dotnet publish -c Release \
    -a ${TARGETARCH} \
    --self-contained true \
    -p:PublishTrimmed=true \
    -p:TrimMode=link \
    -p:PublishSingleFile=true \
    -p:DebugType=None \
    -p:DebugSymbols=false \
    -o /app/publish

FROM alpine:3.19
WORKDIR /app

# Runtime dependencies için gerekli kütüphaneler
RUN apk add --no-cache libstdc++ 

ENV ASPNETCORE_URLS=http://+:5000 \
    DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=true

EXPOSE 5000
COPY --from=build /app/publish .

ENTRYPOINT ["./DateTimeApi"]